services:
  payment-provider:
    image: wiremock/wiremock:3.13.2
    container_name: payment-provider-sandbox
    ports:
      - "8081:8080"
    volumes:
      - ./sandbox/payment-provider/mappings:/home/wiremock/mappings
      - ./sandbox/payment-provider/__files:/home/wiremock/__files